;;; -*- lexical-biding: t -*-

(provide 'camel)

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;                                  camel case                                          ;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(defun region-toggle-camel-case (b e) (interactive "r")
  (let ((dash-found (save-excursion
                      (goto-char b)
                      (search-forward "-" e t)))
        (beg (copy-marker b))
        (end (copy-marker e)))
    (if dash-found
        (progn
         (replace-string "-a" "A" nil beg end)
         (replace-string "-b" "B" nil beg end)
         (replace-string "-c" "C" nil beg end)
         (replace-string "-d" "D" nil beg end)
         (replace-string "-e" "E" nil beg end)
         (replace-string "-f" "F" nil beg end)
         (replace-string "-g" "G" nil beg end)
         (replace-string "-h" "H" nil beg end)
         (replace-string "-i" "I" nil beg end)
         (replace-string "-j" "J" nil beg end)
         (replace-string "-k" "K" nil beg end)
         (replace-string "-l" "L" nil beg end)
         (replace-string "-m" "M" nil beg end)
         (replace-string "-n" "N" nil beg end)
         (replace-string "-o" "O" nil beg end)
         (replace-string "-p" "P" nil beg end)
         (replace-string "-q" "Q" nil beg end)
         (replace-string "-r" "R" nil beg end)
         (replace-string "-s" "S" nil beg end)
         (replace-string "-t" "T" nil beg end)
         (replace-string "-u" "U" nil beg end)
         (replace-string "-w" "W" nil beg end)
         (replace-string "-v" "V" nil beg end)
         (replace-string "-x" "X" nil beg end)
         (replace-string "-y" "Y" nil beg end)
         (replace-string "-z" "Z" nil beg end))
      (progn
        (replace-string "A" "-a" nil beg end)
        (replace-string "B" "-b" nil beg end)
        (replace-string "C" "-c" nil beg end)
        (replace-string "D" "-d" nil beg end)
        (replace-string "E" "-e" nil beg end)
        (replace-string "F" "-f" nil beg end)
        (replace-string "G" "-g" nil beg end)
        (replace-string "H" "-h" nil beg end)
        (replace-string "I" "-i" nil beg end)
        (replace-string "J" "-j" nil beg end)
        (replace-string "K" "-k" nil beg end)
        (replace-string "L" "-l" nil beg end)
        (replace-string "M" "-m" nil beg end)
        (replace-string "N" "-n" nil beg end)
        (replace-string "O" "-o" nil beg end)
        (replace-string "P" "-p" nil beg end)
        (replace-string "Q" "-q" nil beg end)
        (replace-string "R" "-r" nil beg end)
        (replace-string "S" "-s" nil beg end)
        (replace-string "T" "-t" nil beg end)
        (replace-string "U" "-u" nil beg end)
        (replace-string "W" "-w" nil beg end)
        (replace-string "V" "-v" nil beg end)
        (replace-string "X" "-x" nil beg end)
        (replace-string "Y" "-y" nil beg end)
        (replace-string "Z" "-z" nil beg end)))))

