(defun ucode-to-char()
  (interactive)
  (set-mark-command nil)
  (search-backward-regexp "[^0-9a-fA-F]")
  (forward-char 1)
  (let ((v (buffer-substring (region-beginning)(region-end))))
    (kill-region(region-beginning)(region-end))
    (insert-char (string-to-number v 16))))

(global-set-key (kbd "s-x") 'ucode-to-char)


;(defun rereplace(regex str)
;  (goto-char (point-min))
;  (while (re-search-forward regex nil t)
;    (replace-match str)))
;
;
;(defun polish-region(beg end)
;  (interactive "r")
;  (setq end (rereplace-with-bounds beg end " \"" " „"))
;  (setq end (rereplace-with-bounds beg end "\" " "” "))
;  (setq end (rereplace-with-bounds beg end "“" "„"))
;  (setq end (rereplace-with-bounds beg end "«" "„"))
;  (setq end (rereplace-with-bounds beg end "»" "”"))
;  (setq end (rereplace-with-bounds beg end "'" "’"))
;  )
;
;(defun english-region(beg end)
;  (interactive "r")
;  (setq end (rereplace-with-bounds beg end " \"" " “"))
;  (setq end (rereplace-with-bounds beg end "\" " "” "))
;  (setq end (rereplace-with-bounds beg end "„" "“"))
;  (setq end (rereplace-with-bounds beg end "«" "“"))
;  (setq end (rereplace-with-bounds beg end "»" "”"))
;  (setq end (rereplace-with-bounds beg end "'" "’"))
;  (setq end (rereplace-with-bounds beg end "\\([0-9]\\),\\([0-9]\\)" "\\1:\\2"))
;  )

(defun convert-text-region(table beg end)
  "convert a region of text to a different text using the table of replacements"
  (let ((case-fold-search nil)
        (begm (copy-marker beg nil))
        (endm (copy-marker end t)))
    (save-excursion
      (goto-char begm)
      (while (< (point) endm)
                                        ; convert next character
        (let ((p table))
          (while p
            ;(message "trying %s" (caar p))
            (if (looking-at (caar p))
                (progn
                  (delete-char (- (match-end 0) (match-beginning 0)))
                  (insert (cdar p))
                  (message "%s → %s" (caar p) (cdar p))
                  (left-char)
                  (setq p nil))
              (setq p (cdr p)))))
        (right-char)))))

(defun region-toggle-camel-case (b e) (interactive "r")
  (let ((dash-found (save-excursion
                      (goto-char b)
                      (search-forward "-" e t)))
        (beg (copy-marker b))
        (end (copy-marker e)))
    (if dash-found
        (progn
         (replace-string "-a" "A" nil beg end)
         (replace-string "-b" "B" nil beg end)
         (replace-string "-c" "C" nil beg end)
         (replace-string "-d" "D" nil beg end)
         (replace-string "-e" "E" nil beg end)
         (replace-string "-f" "F" nil beg end)
         (replace-string "-g" "G" nil beg end)
         (replace-string "-h" "H" nil beg end)
         (replace-string "-i" "I" nil beg end)
         (replace-string "-j" "J" nil beg end)
         (replace-string "-k" "K" nil beg end)
         (replace-string "-l" "L" nil beg end)
         (replace-string "-m" "M" nil beg end)
         (replace-string "-n" "N" nil beg end)
         (replace-string "-o" "O" nil beg end)
         (replace-string "-p" "P" nil beg end)
         (replace-string "-q" "Q" nil beg end)
         (replace-string "-r" "R" nil beg end)
         (replace-string "-s" "S" nil beg end)
         (replace-string "-t" "T" nil beg end)
         (replace-string "-u" "U" nil beg end)
         (replace-string "-w" "W" nil beg end)
         (replace-string "-v" "V" nil beg end)
         (replace-string "-x" "X" nil beg end)
         (replace-string "-y" "Y" nil beg end)
         (replace-string "-z" "Z" nil beg end))
      (progn
        (replace-string "A" "-a" nil beg end)
        (replace-string "B" "-b" nil beg end)
        (replace-string "C" "-c" nil beg end)
        (replace-string "D" "-d" nil beg end)
        (replace-string "E" "-e" nil beg end)
        (replace-string "F" "-f" nil beg end)
        (replace-string "G" "-g" nil beg end)
        (replace-string "H" "-h" nil beg end)
        (replace-string "I" "-i" nil beg end)
        (replace-string "J" "-j" nil beg end)
        (replace-string "K" "-k" nil beg end)
        (replace-string "L" "-l" nil beg end)
        (replace-string "M" "-m" nil beg end)
        (replace-string "N" "-n" nil beg end)
        (replace-string "O" "-o" nil beg end)
        (replace-string "P" "-p" nil beg end)
        (replace-string "Q" "-q" nil beg end)
        (replace-string "R" "-r" nil beg end)
        (replace-string "S" "-s" nil beg end)
        (replace-string "T" "-t" nil beg end)
        (replace-string "U" "-u" nil beg end)
        (replace-string "W" "-w" nil beg end)
        (replace-string "V" "-v" nil beg end)
        (replace-string "X" "-x" nil beg end)
        (replace-string "Y" "-y" nil beg end)
        (replace-string "Z" "-z" nil beg end)))))

                                        ; https://www.bibleworks.com/fonts.html

(setq bwgrk-to-greek
      '(
        ("VO" . "Ὀ")
        ("VI" . "Ἰ")
        ("VH" . "Ἠ")
        ("VE" . "Ἐ")
        ("VA" . "Ἀ")
        ("~W" . "Ὡ")
        ("~U" . "Ὑ")
        ("~R" . "Ῥ")
        ("~O" . "Ὁ")
        ("~I" . "Ἱ")
        ("~H" . "Ἡ")
        ("~E" . "Ἑ")
        ("~A" . "Ἁ")
        ("\"W" . "Ὢ")
        ("\"O" . "Ὂ")
        ("\"I" . "Ἲ")
        ("\"H" . "Ἢ")
        ("\"E" . "Ἒ")
        ("\"A" . "Ἂ")
        ("}W" . "Ὣ")
        ("}U" . "Ὓ")
        ("}O" . "Ὃ")
        ("}I" . "Ἳ")
        ("}H" . "Ἣ")
        ("}E" . "Ἓ")
        ("}A" . "Ἃ")
        ("W" . "Ὼ")
        ("U" . "Ὺ")
        ("O" . "Ὸ")
        ("I" . "Ὶ")
        ("H" . "Ὴ")
        ("E" . "Ὲ")
        ("A" . "Ὰ")
        ("U" . "Ϋ")
        ("I" . "Ϊ")
        ("+W" . "Ὦ")
        ("+I" . "Ἶ")
        ("+H" . "Ἦ")
        ("+A" . "Ἆ")
        ("_W" . "Ὧ")
        ("_U" . "Ὗ")
        ("_I" . "Ἷ")
        ("_H" . "Ἧ")
        ("_A" . "Ἇ")
        (":W" . "Ὤ")
        (":O" . "Ὄ")
        (":I" . "Ἴ")
        (":H" . "Ἤ")
        (":E" . "Ἔ")
        (":A" . "Ἄ")
        ("{W" . "Ὥ")
        ("{U" . "Ὕ")
        ("{O" . "Ὅ")
        ("{I" . "Ἵ")
        ("{H" . "Ἥ")
        ("{E" . "Ἕ")
        ("{A" . "Ἅ")
        ("W" . "Ώ")
        ("U" . "Ύ")
        ("O" . "Ό")
        ("I" . "Ί")
        ("H" . "Ή")
        ("E" . "Έ")
        ("A" . "Ά")
        ("Z" . "Ζ")
        ("Y" . "Ψ")
        ("X" . "Ξ")
        ("W" . "Ω")
        ("U" . "Υ")
        ("T" . "Τ")
        ("S" . "Σ")
        ("R" . "Ρ")
        ("Q" . "Θ")
        ("P" . "Π")
        ("O" . "Ο")
        ("N" . "Ν")
        ("M" . "Μ")
        ("L" . "Λ")
        ("K" . "Κ")
        ("J" . "Σ")
        ("I" . "Ι")
        ("H" . "Η")
        ("G" . "Γ")
        ("F" . "Φ")
        ("E" . "Ε")
        ("D" . "Δ")
        ("C" . "Χ")
        ("B" . "Β")
        ("A" . "Α")
        ("wv|" . "ᾠ")
        ("hv|" . "ᾐ")
        ("av|" . "ᾀ")
        ("wv" . "ὠ")
        ("uv" . "ὐ")
        ("rv" . "ῤ")
        ("ov" . "ὀ")
        ("iv" . "ἰ")
        ("hv" . "ἠ")
        ("ev" . "ἐ")
        ("av" . "ἀ")
        ("w`|" . "ᾡ")
        ("h`|" . "ᾑ")
        ("a`|" . "ᾁ")
        ("w`" . "ὡ")
        ("u`" . "ὑ")
        ("r`" . "ῥ")
        ("o`" . "ὁ")
        ("i`" . "ἱ")
        ("h`" . "ἡ")
        ("e`" . "ἑ")
        ("a`" . "ἁ")
        ("w]|" . "ᾣ")
        ("h]|" . "ᾓ")
        ("a]|" . "ᾃ")
        ("w[.]|" . "ῲ")
        ("h[.]|" . "ῂ")
        ("a[.]|" . "ᾲ")
        ("w'|" . "ᾢ")
        ("h'|" . "ᾒ")
        ("a'|" . "ᾂ")
        ("w'" . "ὢ")
        ("u'" . "ὒ")
        ("o'" . "ὂ")
        ("i'" . "ἲ")
        ("h'" . "ἢ")
        ("e'" . "ἒ")
        ("a'" . "ἂ")
        ("w]" . "ὣ")
        ("u]" . "ὓ")
        ("o]" . "ὃ")
        ("i]" . "ἳ")
        ("h]" . "ἣ")
        ("e]" . "ἓ")
        ("a]" . "ἃ")
        ("w[.]" . "ὼ")
        ("u[.]" . "ὺ")
        ("o[.]" . "ὸ")
        ("i[.]" . "ὶ")
        ("h[.]" . "ὴ")
        ("e[.]" . "ὲ")
        ("a[.]" . "ὰ")
        ("υ>" . "ῢ")
        ("u\\?" . "ϋ")
        ("i\\?" . "ϊ")
        ("w=" . "ὦ")
        ("u=" . "ὖ")
        ("i=" . "ἶ")
        ("h=" . "ἦ")
        ("a=" . "ἆ")
        ("w-" . "ὧ")
        ("u-" . "ὗ")
        ("i-" . "ἷ")
        ("h-" . "ἧ")
        ("a-" . "ἇ")
        ("w=|" . "ᾦ")
        ("h=|" . "ᾖ")
        ("a=|" . "ᾆ")
        ("w-|" . "ᾧ")
        ("h-|" . "ᾗ")
        ("a-|" . "ᾇ")
        ("w/|" . "ῷ")
        ("h/|" . "ῇ")
        ("a/|" . "ᾷ")
        ("w/" . "ῶ")
        ("u/" . "ῦ")
        ("i/" . "ῖ")
        ("h/" . "ῆ")
        ("a/" . "ᾶ")
        ("w;|" . "ᾤ")
        ("h;|" . "ᾔ")
        ("a;|" . "ᾄ")
        ("w;" . "ὤ")
        ("u;" . "ὔ")
        ("o;" . "ὄ")
        ("i;" . "ἴ")
        ("h;" . "ἤ")
        ("e;" . "ἔ")
        ("a;" . "ἄ")
        ("w\\[|" . "ᾥ")
        ("h\\[|" . "ᾕ")
        ("a\\[|" . "ᾅ")
        ("w\\[" . "ὥ")
        ("u\\[" . "ὕ")
        ("o\\[" . "ὅ")
        ("i\\[" . "ἵ")
        ("h\\[" . "ἥ")
        ("e\\[" . "ἕ")
        ("a\\[" . "ἅ")
        ("w,|" . "ῴ")
        ("h,|" . "ῄ")
        ("a,|" . "ᾴ")
        ("i,\\?" . "ΐ")
        ("i,\\?" . "ΐ")
        ("w," . "ώ")
        ("w," . "ώ")
        ("u," . "ύ")
        ("u," . "ύ")
        ("o," . "ό")
        ("o," . "ό")
        ("i," . "ί")
        ("i," . "ί")
        ("h," . "ή")
        ("h," . "ή")
        ("e," . "έ")
        ("e," . "έ")
        ("a," . "ά")
        ("a," . "ά")
        ("w|" . "ῳ")
        ("h|" . "ῃ")
        ("a|" . "ᾳ")
        ("z" . "ζ")
        ("y" . "ψ")
        ("x" . "ξ")
        ("w" . "ω")
        ("u" . "υ")
        ("t" . "τ")
        ("s" . "σ")
        ("r" . "ρ")
        ("q" . "θ")
        ("p" . "π")
        ("o" . "ο")
        ("n" . "ν")
        ("m" . "μ")
        ("l" . "λ")
        ("k" . "κ")
        ("j" . "ς")
        ("i" . "ι")
        ("h" . "η")
        ("g" . "γ")
        ("f" . "φ")
        ("e" . "ε")
        ("d" . "δ")
        ("c" . "χ")
        ("b" . "β")
        ("a" . "α")
        ("(" . ",")
        (")" . ".")
        ("Å" . ".")
        ("È" . ";")
        ("Î" . "[")
        ("Ð" . "]")
        ("V" . "’")
        ("\\\\" . "·")
        ))

(defun greek-from-bwgrk-region(beg end)
  (interactive "r")
  (convert-text-region bwgrk-to-greek beg end))

(setq greek-to-bwgrk
      '(
        ("Ὀ" . "VO")
        ("Ἰ" . "VI")
        ("Ἠ" . "VH")
        ("Ἐ" . "VE")
        ("Ἀ" . "VA")
        ("Ὡ" . "~W")
        ("Ὑ" . "~U")
        ("Ῥ" . "~R")
        ("Ὁ" . "~O")
        ("Ἱ" . "~I")
        ("Ἡ" . "~H")
        ("Ἑ" . "~E")
        ("Ἁ" . "~A")
        ("Ὢ" . "\"W")
        ("Ὂ" . "\"O")
        ("Ἲ" . "\"I")
        ("Ἢ" . "\"H")
        ("Ἒ" . "\"E")
        ("Ἂ" . "\"A")
        ("Ὣ" . "}W")
        ("Ὓ" . "}U")
        ("Ὃ" . "}O")
        ("Ἳ" . "}I")
        ("Ἣ" . "}H")
        ("Ἓ" . "}E")
        ("Ἃ" . "}A")
        ("Ὼ" . "W")
        ("Ὺ" . "U")
        ("Ὸ" . "O")
        ("Ὶ" . "I")
        ("Ὴ" . "H")
        ("Ὲ" . "E")
        ("Ὰ" . "A")
        ("Ϋ" . "U")
        ("Ϊ" . "I")
        ("Ὦ" . "+W")
        ("Ἶ" . "+I")
        ("Ἦ" . "+H")
        ("Ἆ" . "+A")
        ("Ὧ" . "_W")
        ("Ὗ" . "_U")
        ("Ἷ" . "_I")
        ("Ἧ" . "_H")
        ("Ἇ" . "_A")
        ("Ὤ" . ":W")
        ("Ὄ" . ":O")
        ("Ἴ" . ":I")
        ("Ἤ" . ":H")
        ("Ἔ" . ":E")
        ("Ἄ" . ":A")
        ("Ὥ" . "{W")
        ("Ὕ" . "{U")
        ("Ὅ" . "{O")
        ("Ἵ" . "{I")
        ("Ἥ" . "{H")
        ("Ἕ" . "{E")
        ("Ἅ" . "{A")
        ("Ώ" . "W")
        ("Ύ" . "U")
        ("Ό" . "O")
        ("Ί" . "I")
        ("Ή" . "H")
        ("Έ" . "E")
        ("Ά" . "A")
        ("Ζ" . "Z")
        ("Ψ" . "Y")
        ("Ξ" . "X")
        ("Ω" . "W")
        ("Υ" . "U")
        ("Τ" . "T")
        ("Σ" . "S")
        ("Ρ" . "R")
        ("Θ" . "Q")
        ("Π" . "P")
        ("Ο" . "O")
        ("Ν" . "N")
        ("Μ" . "M")
        ("Λ" . "L")
        ("Κ" . "K")
        ("Σ" . "J")
        ("Ι" . "I")
        ("Η" . "H")
        ("Γ" . "G")
        ("Φ" . "F")
        ("Ε" . "E")
        ("Δ" . "D")
        ("Χ" . "C")
        ("Β" . "B")
        ("Α" . "A")
        ("ὠ" . "wv")
        ("ὐ" . "uv")
        ("ῤ" . "rv")
        ("ὀ" . "ov")
        ("ἰ" . "iv")
        ("ἠ" . "hv")
        ("ἐ" . "ev")
        ("ἀ" . "av")
        ("ὡ" . "w`")
        ("ὑ" . "u`")
        ("ῥ" . "r`")
        ("ὁ" . "o`")
        ("ἱ" . "i`")
        ("ἡ" . "h`")
        ("ἑ" . "e`")
        ("ἁ" . "a`")
        ("ᾢ" . "w'|")
        ("ᾒ" . "h'|")
        ("ᾂ" . "a'|")
        ("ᾣ" . "w]|")
        ("ᾓ" . "h]|")
        ("ᾃ" . "a]|")
        ("ῲ" . "w.|")
        ("ῂ" . "h.|")
        ("ᾲ" . "a.|")
        ("ᾠ" . "wv|")
        ("ᾐ" . "hv|")
        ("ᾀ" . "av|")
        ("ᾡ" . "w`|")
        ("ᾑ" . "h`|")
        ("ᾁ" . "a`|")
        ("ῳ" . "w|")
        ("ῃ" . "h|")
        ("ᾳ" . "a|")
        ("ὢ" . "w'")
        ("ὒ" . "u'")
        ("ὂ" . "o'")
        ("ἲ" . "i'")
        ("ἢ" . "h'")
        ("ἒ" . "e'")
        ("ἂ" . "a'")
        ("ὣ" . "w]")
        ("ὓ" . "u]")
        ("ὃ" . "o]")
        ("ἳ" . "i]")
        ("ἣ" . "h]")
        ("ἓ" . "e]")
        ("ἃ" . "a]")
        ("ὼ" . "w.")
        ("ὺ" . "u.")
        ("ὸ" . "o.")
        ("ὶ" . "i.")
        ("ὴ" . "h.")
        ("ὲ" . "e.")
        ("ὰ" . "a.")
        ("ῢ" . "υ>")
        ("ϋ" . "u?")
        ("ϊ" . "i?")
        ("ὦ" . "w=")
        ("ὖ" . "u=")
        ("ἶ" . "i=")
        ("ἦ" . "h=")
        ("ἆ" . "a=")
        ("ὧ" . "w-")
        ("ὗ" . "u-")
        ("ἷ" . "i-")
        ("ἧ" . "h-")
        ("ἇ" . "a-")
        ("ᾦ" . "w=|")
        ("ᾖ" . "h=|")
        ("ᾆ" . "a=|")
        ("ᾧ" . "w-|")
        ("ᾗ" . "h-|")
        ("ᾇ" . "a-|")
        ("ῷ" . "w/|")
        ("ῇ" . "h/|")
        ("ᾷ" . "a/|")
        ("ῶ" . "w/")
        ("ῦ" . "u/")
        ("ῖ" . "i/")
        ("ῆ" . "h/")
        ("ᾶ" . "a/")
        ("ᾤ" . "w;|")
        ("ᾔ" . "h;|")
        ("ᾄ" . "a;|")
        ("ὤ" . "w;")
        ("ὔ" . "u;")
        ("ὄ" . "o;")
        ("ἴ" . "i;")
        ("ἤ" . "h;")
        ("ἔ" . "e;")
        ("ἄ" . "a;")
        ("ᾥ" . "w[|")
        ("ᾕ" . "h[|")
        ("ᾅ" . "a[|")
        ("ὥ" . "w[")
        ("ὕ" . "u[")
        ("ὅ" . "o[")
        ("ἵ" . "i[")
        ("ἥ" . "h[")
        ("ἕ" . "e[")
        ("ἅ" . "a[")
        ("ῴ" . "w,|")
        ("ῄ" . "h,|")
        ("ᾴ" . "a,|")
        ("ΐ" . "i,?")
        ("ΐ" . "i,?")
        ("ώ" . "w,")
        ("ώ" . "w,")
        ("ύ" . "u,")
        ("ύ" . "u,")
        ("ό" . "o,")
        ("ό" . "o,")
        ("ί" . "i,")
        ("ί" . "i,")
        ("ή" . "h,")
        ("ή" . "h,")
        ("έ" . "e,")
        ("έ" . "e,")
        ("ά" . "a,")
        ("ά" . "a,")
        ("ζ" . "z")
        ("ψ" . "y")
        ("ξ" . "x")
        ("ω" . "w")
        ("υ" . "u")
        ("τ" . "t")
        ("σ" . "s")
        ("ρ" . "r")
        ("θ" . "q")
        ("π" . "p")
        ("ο" . "o")
        ("ν" . "n")
        ("μ" . "m")
        ("λ" . "l")
        ("κ" . "k")
        ("ς" . "j")
        ("ι" . "i")
        ("η" . "h")
        ("γ" . "g")
        ("φ" . "f")
        ("ε" . "e")
        ("δ" . "d")
        ("χ" . "c")
        ("β" . "b")
        ("α" . "a")
        ("," . "(")
        ("[.]" . ")")
        ("·" . "\\")
        ))


(defun greek-to-bwgrk-region(beg end)
  (interactive "r")
  (convert-text-region greek-to-bwgrk beg end))


(setq greek-transliteration
      '(
        ("Ὀ" . "O")
        ("Ἰ" . "I")
        ("Ἠ" . "Ē")
        ("Ἐ" . "E")
        ("Ἀ" . "A")
        ("Ὡ" . "hŌ")
        ("Ὑ" . "hY")
        ("Ῥ" . "hR")
        ("Ὁ" . "hO")
        ("Ἱ" . "hI")
        ("Ἡ" . "hĒ")
        ("Ἑ" . "hE")
        ("Ἁ" . "hA")
        ("Ὢ" . "Ō")
        ("Ὂ" . "O")
        ("Ἲ" . "I")
        ("Ἢ" . "Ē")
        ("Ἒ" . "E")
        ("Ἂ" . "A")
        ("Ὣ" . "hŌ")
        ("Ὓ" . "hY")
        ("Ὃ" . "hO")
        ("Ἳ" . "hI")
        ("Ἣ" . "hĒ")
        ("Ἓ" . "hE")
        ("Ἃ" . "hA")
        ("Ὼ" . "Ō")
        ("Ὺ" . "Y")
        ("Ὸ" . "O")
        ("Ὶ" . "I")
        ("Ὴ" . "Ē")
        ("Ὲ" . "E")
        ("Ὰ" . "A")
        ("Ϋ" . "Y")
        ("Ϊ" . "I")
        ("Ὦ" . "Ō")
        ("Ἶ" . "I")
        ("Ἦ" . "Ē")
        ("Ἆ" . "A")
        ("Ὧ" . "hŌ")
        ("Ὗ" . "hY")
        ("Ἷ" . "hI")
        ("Ἧ" . "hĒ")
        ("Ἇ" . "hA")
        ("Ὤ" . "Ō")
        ("Ὄ" . "O")
        ("Ἴ" . "I")
        ("Ἤ" . "Ē")
        ("Ἔ" . "E")
        ("Ἄ" . "A")
        ("Ὥ" . "hŌ")
        ("Ὕ" . "hY")
        ("Ὅ" . "hO")
        ("Ἵ" . "hI")
        ("Ἥ" . "hĒ")
        ("Ἕ" . "hE")
        ("Ἅ" . "hA")
        ("Ώ" . "Ō")
        ("Ύ" . "Y")
        ("Ό" . "O")
        ("Ί" . "I")
        ("Ή" . "Ē")
        ("Έ" . "E")
        ("Ά" . "A")
        ("Ζ" . "Z")
        ("Ψ" . "Y")
        ("Ξ" . "X")
        ("Ω" . "Ō")
        ("Υ" . "Y")
        ("Τ" . "T")
        ("Σ" . "S")
        ("Ρ" . "R")
        ("Θ" . "TH")
        ("Π" . "P")
        ("Ο" . "O")
        ("Ν" . "N")
        ("Μ" . "M")
        ("Λ" . "L")
        ("Κ" . "K")
        ("Σ" . "S")
        ("Ι" . "I")
        ("Η" . "Ē")
        ("Γ" . "G")
        ("Φ" . "PH")
        ("Ε" . "E")
        ("Δ" . "D")
        ("Χ" . "CH")
        ("Β" . "B")
        ("Α" . "A")
        ("ὠ" . "ō")
        ("αὐ" . "au")
        ("εὐ" . "eu")
        ("οὐ" . "ou")
        ("ὐ" . "y")
        ("ῤ" . "r")
        ("ὀ" . "o")
        ("υἰ" . "ui")
        ("ἰ" . "i")
        ("ἠ" . "ē")
        ("ἐ" . "e")
        ("ἀ" . "a")
        ("ὡ" . "hō")
        ("αὑ" . "hau")
        ("οὑ" . "hou")
        ("ὑ" . "hy")
        ("ῥ" . "hr")
        ("ὁ" . "ho")
        ("αἱ" . "hai")
        ("εἱ" . "hei")
        ("υἱ" . "hui")
        ("ἱ" . "hi")
        ("ἡ" . "hē")
        ("ἑ" . "he")
        ("ἁ" . "ha")
        ("ᾢ" . "ōᵢ")
        ("ᾒ" . "ēᵢ")
        ("ᾂ" . "aᵢ")
        ("ᾣ" . "hōᵢ")
        ("ᾓ" . "hēᵢ")
        ("ᾃ" . "haᵢ")
        ("ῲ" . "ōᵢ")
        ("ῂ" . "ēᵢ")
        ("ᾲ" . "aᵢ")
        ("ᾠ" . "ōᵢ")
        ("ᾐ" . "ēᵢ")
        ("ᾀ" . "aᵢ")
        ("ᾡ" . "hōᵢ")
        ("ᾑ" . "hēᵢ")
        ("ᾁ" . "haᵢ")
        ("ῳ" . "ōᵢ")
        ("ῃ" . "ēᵢ")
        ("ᾳ" . "aᵢ")
        ("ὢ" . "ō")
        ("αὒ" . "au")
        ("εὒ" . "eu")
        ("οὒ" . "ou")
        ("ὒ" . "y")
        ("ὂ" . "o")
        ("υἲ" . "ui")
        ("ἲ" . "i")
        ("ἢ" . "ē")
        ("ἒ" . "e")
        ("ἂ" . "a")
        ("ὣ" . "hō")
        ("αὓ" . "hau")
        ("εὓ" . "heu")
        ("οὓ" . "hou")
        ("ὓ" . "hy")
        ("ὃ" . "ho")
        ("αἳ" . "hai")
        ("εἳ" . "hei")
        ("υἳ" . "hui")
        ("ἳ" . "hi")
        ("ἣ" . "hē")
        ("ἓ" . "he")
        ("ἃ" . "ha")
        ("ὼ" . "ō")
        ("αὺ" . "au")
        ("εὺ" . "eu")
        ("οὺ" . "ou")
        ("ὺ" . "y")
        ("ὸ" . "o")
        ("υὶ" . "ui")
        ("ὶ" . "i")
        ("ὴ" . "ē")
        ("ὲ" . "e")
        ("ὰ" . "a")
        ("ῢ" . "y")
        ("ϋ" . "y")
        ("ϊ" . "i")
        ("ὦ" . "ō")
        ("αὖ" . "au")
        ("εὖ" . "eu")
        ("οὖ" . "ou")
        ("ὖ" . "y")
        ("υἶ" . "ui")
        ("ἶ" . "i")
        ("ἦ" . "ē")
        ("ἆ" . "a")
        ("ὧ" . "hō")
        ("αὗ" . "hau")
        ("οὗ" . "hou")
        ("ὗ" . "hy")
        ("αἷ" . "hai")
        ("εἷ" . "hei")
        ("υἷ" . "hui")
        ("ἷ" . "hi")
        ("ἧ" . "hē")
        ("ἇ" . "ha")
        ("ᾦ" . "ōᵢ")
        ("ᾖ" . "ēᵢ")
        ("ᾆ" . "aᵢ")
        ("ᾧ" . "hōᵢ")
        ("ᾗ" . "hēᵢ")
        ("ᾇ" . "haᵢ")
        ("ῷ" . "ōᵢ")
        ("ῇ" . "ēᵢ")
        ("ᾷ" . "aᵢ")
        ("ῶ" . "ō")
        ("αῦ" . "au")
        ("εῦ" . "eu")
        ("οῦ" . "ou")
        ("ῦ" . "y")
        ("υῖ" . "ui")
        ("ῖ" . "i")
        ("ῆ" . "ē")
        ("ᾶ" . "a")
        ("ᾤ" . "ōᵢ")
        ("ᾔ" . "ēᵢ")
        ("ᾄ" . "aᵢ")
        ("ὤ" . "ō")
        ("αὔ" . "au")
        ("εὔ" . "eu")
        ("οὔ" . "ou")
        ("ὔ" . "y")
        ("ὄ" . "o")
        ("υἴ" . "ui")
        ("ἴ" . "i")
        ("ἤ" . "ē")
        ("ἔ" . "e")
        ("ἄ" . "a")
        ("ᾥ" . "hōᵢ")
        ("ᾕ" . "hēᵢ")
        ("ᾅ" . "haᵢ")
        ("ὥ" . "hō")
        ("αὕ" . "hau")
        ("εὕ" . "heu")
        ("οὕ" . "hou")
        ("ὕ" . "hy")
        ("ὅ" . "ho")
        ("αἵ" . "hai")
        ("υἵ" . "hui")
        ("ἵ" . "hi")
        ("ἥ" . "hē")
        ("ἕ" . "he")
        ("ἅ" . "ha")
        ("ῴ" . "ōᵢ")
        ("ῄ" . "ēᵢ")
        ("ᾴ" . "aᵢ")
        ("ΐ" . "i")
        ("ΐ" . "i")
        ("ώ" . "ō")
        ("ώ" . "ō")
        ("αύ" . "au")
        ("εύ" . "eu")
        ("ού" . "ou")
        ("ύ" . "y")
        ("αύ" . "au")
        ("ού" . "ou")
        ("ύ" . "y")
        ("ό" . "o")
        ("ό" . "o")
        ("υί" . "ui")
        ("υί" . "ui")
        ("ί" . "i")
        ("ί" . "i")
        ("ή" . "ē")
        ("ή" . "ē")
        ("έ" . "e")
        ("έ" . "e")
        ("ά" . "a")
        ("ά" . "a")
        ("ζ" . "z")
        ("ψ" . "ps")
        ("ξ" . "x")
        ("ω" . "ō")
        ("αυ" . "au")
        ("ευ" . "eu")
        ("ου" . "ou")
        ("υι" . "ui")
        ("υ" . "y")
        ("τ" . "t")
        ("σ" . "s")
        ("ρ" . "r")
        ("θ" . "th")
        ("π" . "p")
        ("ο" . "o")
        ("ν" . "n")
        ("μ" . "m")
        ("λ" . "l")
        ("κ" . "k")
        ("ς" . "s")
        ("ι" . "i")
        ("η" . "ē")
        ("γ" . "g")
        ("φ" . "ph")
        ("ε" . "e")
        ("δ" . "d")
        ("χ" . "ch")
        ("β" . "b")
        ("α" . "a")
        ))

(defun greek-transliterate-region(beg end)
  (interactive "r")
  (convert-text-region greek-transliteration beg end))

(global-set-key (kbd "C-c G t") 'greek-transliterate-region)
(global-set-key (kbd "C-c G b") 'greek-to-bwgrk-region)
(global-set-key (kbd "C-c G B") 'greek-from-bwgrk-region)
